### ISSUE TITLE
Using text and command inside a property leads to parse error

### ISSUE THREAD

**Issue by Florob** [latex-lsp/tree-sitter-latex#13] opened 2021-08-22 00:23 UTC
Relatively common code like
```latex
\includegraphics[width=0.5\textwidth]{some.jpg}
```
leads to a parse error inside the property.

`width` is correctly interpreted as key, but the value stops after `0.5` making the `\textwidth` an error.

**Comment by pfoerster** [comment] 2022-02-02 20:33
Thanks for the report. The issue is now fixed on the master branch.

**Closed by pfoerster** 2022-02-02 20:33 UTC
Labels: bug
