### ISSUE TITLE
Parse error with special characters

### ISSUE THREAD

**Issue by symphorien** [latex-lsp/tree-sitter-latex#11] opened 2021-08-10 16:30 UTC
Consider the following file:
```
\documentclass{article}
\begin{document}

\texttt{foo :("@@@} foo foo
foo foo \texttt{0xffe00fff} foo foo foo foo foo foo foo foo foo foo foo
foo \texttt{0xfff00000}.

foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo
foo.  foo foo foo foo foo foo foo foo foo foo
foo foo foo foo foo foo
\end{document}
```
it is compiled without warning by latex, but the grammar fails:
```
foo.tex	0 ms	(MISSING "]" [3, 18] - [3, 18])
```

**Comment by pfoerster** [comment] 2022-02-02 20:33
Thanks for the example. The issue is fixed on the master branch. Actually, it was caused by unbalanced parentheses/brackets, which are now only matched when required.

**Closed by pfoerster** 2022-02-02 20:33 UTC
